### ISSUE TITLE
#all, #first, #last, etc are unavailable if 'design' section is omitted in model

### ISSUE THREAD

**Issue by debdude** [couchrest/couchrest_model#195]
Older sample apps fail to work, and readme does not mention it, so it kept me confused for some time.

Model is:
```
class Case < CouchRest::Model::Base
    use_database 'cases'
    property :_id, String 
    property :name, String 
    property :person_id, String 
    property :info, String 
    property :state, String 
    property :description, String 
    timestamps!

	# design do
 #     	view :by_name
 #  	end

end
```

```
2.2.2 :004 >   Case.find('806f380a1be2b7443a64948bf4411ff9')
 => #<Case _id: "806f380a1be2b7443a64948bf4411ff9", name: "blah blah", person_id: "d3209328", info: "info info", state: "ok", description: nil, updated_at: 2015-09-19 12:38:28 UTC, created_at: 2015-09-19 12:38:28 UTC, _rev: "1-44de5d24e84af6257f115479367108bb", type: "Case"> 
2.2.2 :005 > Case.all
NoMethodError: undefined method `all' for Case:Class
	from (irb):5
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /home/dy/tmp/co2/bin/rails:8:in `<top (required)>'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/commands/rails.rb:6:in `call'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/command_wrapper.rb:38:in `call'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:183:in `block in serve'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:156:in `fork'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:156:in `serve'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /home/dy/.rvm/gems/ruby-2.2.2@couch/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/dy/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/dy/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.2 :006 > 

```

**Comment by samlown** [comment]
Hi! You can't query documents without a design document in CouchRest Model. You should however by able to call get on the id: `Case.get('806f380a1be2b7443a64948bf4411ff9')`

**Comment by debdude** [comment]
exactly, and this is not mentioned in the Readme nor elsewhere, which is quite confusing

**Comment by samlown** [comment]
I can appreciate that, although this is a limitation of CouchDB more than CouchRest Model. If you'd like to send a pull request with your suggested changes to the docs, more than happy to accept them.
